#!/bin/bash

#SBATCH -J L2_PINNs
#SBATCH -p gtx
#SBATCH -N 1
#SBATCH -n 9
#SBATCH -t 24:00:00
#SBATCH --mail-user=jonathan.wittmer@utexas.edu
#SBATCH --mail-type=all

$WORK/Machine_Learning/load_tf_modules.sh
ibrun ./scheduler.py
